swagger: "2.0"
info:
  description: "Welcome to this REST API for the [nsblast](https://github.com/jgaa/nsblast) authoritative DNS server"
  version: "1.0.0"
  title: "nsBLAST API"
  #termsOfService: "http://swagger.io/terms/"
  contact:
    email: "jarle@jgaa.com"
  license:
    name: "GNU General Public License v3.0"
    url: "https://github.com/jgaa/nsblast/blob/main/LICENSE"
#host: "petstore.swagger.io"
basePath: "/api/v1"
tags:
- name: "zone"
  description: "DNS Zone"
  # externalDocs:
  #   description: "A zone is an administrative unit in the DNS hirarcy"
  #   url: "http://swagger.io"
- name: rr
  description: Operations about an individual DNS entry's resource record(s)
- name: "tenant"
  description: "Operations about a tenant"
- name: "user"
  description: "Operations about a user"
- name: "namespace"
  description: "Operations about a namespace"

# schemes:
# - "https"
# - "http"
paths:
  /zone/{zonename}:
    parameters:
    - in: path
      name: zonename
      description: "Unique fqdn of a DNS zone, for example: 'example.com'"
      required: true
      type: string
    post:
      tags:
      - zone
      summary: "Create a new zone to the default namespace"
      description: "A new zone is added if the fqdn is available (in nsblasts internal database)."
      operationId: "addZone"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Settings for the Zone. Soa and two ns records *must* be present."
        required: true
        schema:
          $ref: "#/definitions/Entry"
      responses:
        "400":
          description: "Invalid input"
        "409":
          description: "Zone already exist"
          
    delete:
      tags:
      - zone
      summary: Deletes an existing zone
      description: "Deletes a zone and all it's domain name entries."       
      responses:
        "404":
          description: "Zone not found"

  /rr/{fqdn}:
    parameters:
    - in: path
      name: fqdn
      description: "fqdn to change, for example: 'www.example.com' The 'rr' entries contain a, aaa, cname and txt resource records for any fqdn. The Zone and Zone ownership is deduced from the fqdn. You can only uise fqdn's for zones already created under your account."
      required: true
      type: string

    post:
      tags:
      - rr
      summary: Add a new fqdn entry with resource records
      description: "A new fqdn is added. Note that if you have a zone example.com, and you want to associate it with a ip address, you can use POST to create a new resource record with a/aaaa values in it."
      operationId: "addFdqn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: Resource records for the fqdn
        required: true
        schema:
          $ref: "#/definitions/Entry"
      responses:
        "400":
          description: Invalid input
        "403":
          description: Zone not created or not owned by your account
        "409":
          description: fqdn already exist
          
    put:
      tags:
      - rr
      summary: Replace the resource records for an existing fqdn
      description: ""
      operationId: "putFdqn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Settings for the Zone"
        required: true
        schema:
          $ref: "#/definitions/Entry"
      responses:
        "400":
          description: Invalid input
        "403":
          description: Zone not created or not owned by your account
        "404":
          description: Fdqn not found
    patch:
      tags:
      - rr
      summary: Create a new fqdn or update/merge an existing fqdn
      description: "Convenience method, like 'upsert' in a database operation. Note that only declared properties will be merged. For example, if you want to switch from cname to a/aaaa records, you specify 'cname' as an empty string and populate a and aaaa arrays with ip numbers. Or, if you don't specify for example 'txt', its value will remain unchanged."
      operationId: "patchFdqn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: Resource records for the fqdn
        required: true
        schema:
          $ref: "#/definitions/Entry"
      responses:
        "400":
          description: Invalid input
        "403":
          description: Zone not created or not owned by your account
        "404":
          description: Fdqn not found
    delete:
      tags:
      - rr
      operationId: "deleteFdqn"
      summary: Deletes an existing fqdn
      description: "Deletes a fqdn and all it's resource records (except nn and soa, which are kept in the zone itself). For example, if you delete 'example.com', that means that the resource records are gone, exept the dns information and the soa properties."
      responses:
        "403":
          description: Zone not created or not owned by your account
        "404":
          description: Fdqn not found
          
  /rr/{fqdn}/{rrname}:
    parameters:
    - in: path
      name: fqdn
      description: "fqdn to delete, for example: 'www.example.com' The Zone and Zone ownership is deduced from the fqdn. You can only use fqdn's for zones already created under your account."
      required: true
      type: string
      
    - in: path
      name: rrname
      required: true
      type: string
      description: "Narrows the request to a specific resource type. One of: a, aaaa, cname, txt"
    delete:
      tags:
      - rr
      operationId: "deleteFdqnRr"
      summary: Deletes a resource record from an existing fqdn
      description: "Deletes the specified resource record from a fqdn. If no resource records remains, the fqdn is deleted as well."
      responses:
        "403":
          description: Zone not created or not owned by your account
        "404":
          description: Fdqn not found
          
definitions:

  Uuid:
    type: object
    properties:
      id:
        type: string
      
      
  Soa:
    type: object
    properties:
      ttl:
        type: integer
        description: Time in seconds that DNS servers can cache the zone before they need to refresh their cache
      refresh:
        type: integer
      retry:
        type: integer
      expire:
        type: integer
      minimum:
        type: integer
      mname:
        type: string
        description: Primar DNS server fqdn
      rname:
        description: Weird, legacy email-name without '@'.
      
  Ns:
    type: array
    items:
      type: string
        
  Zone:
    type: object
    description: A DNS zone. All the properties are optional. Reasonable defaults will be set for omitted items. 
    properties:
      soa:
        $ref: "#/definitions/Soa"
      ns:
        $ref: "#/definitions/Ns"
  Rra:
    type: array
    description: Resource type for A (ipv4 and ipv6) entries.
    items:
      type: string
      
  Mx:
    type: array
    items:
      properties:
        priority:
          type: integer
        host:
          type: string
        
  Entry:
    type: object
    properties:
      a:
        $ref: "#/definitions/Rra"
      txt:
        type: string
      cname:
        type: string
        description: Redirect to another fqdn. If used, a and aaaa must be empty
      mx:
        $ref: "#/definitions/Mx"
      soa:
        $ref: "#/definitions/Soa"
      ns:
        $ref: "#/definitions/Ns"

    
  
externalDocs:
  description: "Find out more about nsBLAST and ready to go hosting options"
  url: "https://nsblast.com"
