version: "3.0"

services:
  master:
    image: jgaafromnorth/nsblast
    environment:
        - NSBLAST_ADMIN_PASSWORD=VerySecret
        - NSBLAST_CLUSTER_AUTH_KEY=VeryMoreSecret
    command: --dns-endpoint 0.0.0.0 --http-endpoint 0.0.0.0 --log-to-console trace --http-port 80 --cluster-role primary --cluster-server-address 0.0.0.0:10123
    # The cursed avahi-daemon use udp port 5353, so we can't safely use that :/
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:5354:53/tcp"
      - "127.0.0.1:5354:53/udp"

  slave1:
    image: jgaafromnorth/nsblast
    environment:
        - NSBLAST_ADMIN_PASSWORD=VerySecret
        - NSBLAST_CLUSTER_AUTH_KEY=VeryMoreSecret
    command: --dns-endpoint 0.0.0.0 --http-endpoint 0.0.0.0 --log-to-console trace --http-port 80 --cluster-role follower --cluster-server-address master:10123
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:5355:53/tcp"
      - "127.0.0.1:5355:53/udp"
      
  slave2:
    image: jgaafromnorth/nsblast
    environment:
        - NSBLAST_ADMIN_PASSWORD=VerySecret
        - NSBLAST_CLUSTER_AUTH_KEY=VeryMoreSecret
    command: --dns-endpoint 0.0.0.0 --http-endpoint 0.0.0.0 --log-to-console trace --http-port 80 --cluster-role follower --cluster-server-address master:10123
    ports:
      - "127.0.0.1:8082:80"
      - "127.0.0.1:5356:53/tcp"
      - "127.0.0.1:5356:53/udp"
